- name: Running DeploymentConfig
  block:
  - set_fact:
      namespace: "prune"

  - name: Ensure namespace
    kubernetes.core.k8s:
      kind: namespace
      name: "{{ namespace }}"
      wait: yes

  - name: Ensure namespace
    kubernetes.core.k8s:
      namespace: "{{ namespace }}"
      wait: yes
      wait_condition:
        type: Available
        status: True
      definition:
        kind: DeploymentConfig
        apiVersion: apps.openshift.io/v1
        metadata:
          name: front
        spec:
          replicas: 2
          template:
            metadata:
              labels:
                name: test
            spec:
              containers:
                - args:
                  - /bin/sh
                  - -c
                  - while true; do echo $(date); sleep 15; done
                  image: python:3.7-alpine
                  imagePullPolicy: Always
                  name: python
          selector:
            name: test
          strategy:
            type: Rolling

  - name: Wait for resource creation
    pause:
      seconds: 60

  - name: Display Pod
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: '{{ namespace }}'
    register: result

  - name: Debug resources
    debug: var=result

  - name: Display ReplicationController
    kubernetes.core.k8s_info:
      kind: ReplicationController
      namespace: '{{ namespace }}'
    register: result

  - name: Debug resources
    debug: var=result

  - name: Display DeploymentConfig
    kubernetes.core.k8s_info:
      kind: ReplicationController
      namespace: '{{ namespace }}'
      name: front
    register: result

  - name: Debug resources
    debug: var=result

  always:
    - name: Delete namespace
      kubernetes.core.k8s:
        kind: namespace
        name: "{{ namespace }}"
        state: absent
      ignore_errors: true
